import type { MissionControlData } from "./types";

const generatedAt = new Date().toISOString();

export const MOCK_MISSION_CONTROL: MissionControlData = {
  greetingName: "Rusty",
  operationalSummary:
    "Eight items need your attention across approvals, delivery failures, and new outcomes. Four agents are executing while the rest of the system remains stable.",
  generatedAt,
  freshness: "mock",
  stale: false,
  context: [
    { id: "organization", label: "Organization", value: "Avraxe", options: ["Avraxe", "Titan ICF"] },
    { id: "workspace", label: "Workspace", value: "Development", options: ["Development", "Marketing", "Research"] },
    { id: "project", label: "Project", value: "Sentinel OS", options: ["Sentinel OS", "Titan ICF SEO", "Range Console"] },
    { id: "team", label: "Agent Team", value: "Hermes + Claude", options: ["Hermes + Claude", "Codex", "All agents"] },
    { id: "scope", label: "Knowledge Scope", value: "Project", options: ["Project", "Workspace", "Organization"] },
  ],
  summaryMetrics: [
    { id: "approvals", label: "Urgent approvals", value: 3, detail: "Need your decision", tone: "critical", actionLabel: "Review now", href: "/workflows" },
    { id: "failures", label: "Failed jobs", value: 2, detail: "Require attention", tone: "warning", actionLabel: "View failures", href: "/workflows" },
    { id: "agents", label: "Active agents", value: 4, detail: "Running now", tone: "positive", actionLabel: "View agents", href: "/agents" },
    { id: "outcomes", label: "New outcomes", value: 6, detail: "Captured overnight", tone: "neutral", actionLabel: "Review outcomes", href: "/projects" },
    { id: "knowledge", label: "Pending knowledge", value: 12, detail: "Candidates to review", tone: "warning", actionLabel: "Review candidates", href: "/memory" },
  ],
  continueItems: [
    { id: "continue-1", type: "project", title: "Sentinel Mission Control", context: "Project · UI implementation", lastActivity: "45 min ago", status: "In progress", href: "/projects" },
    { id: "continue-2", type: "conversation", title: "Neural graph direction", context: "Conversation · Hermes Lisa", lastActivity: "1 hr ago", status: "Ready", href: "/chat" },
    { id: "continue-3", type: "file", title: "mission-control-spec.md", context: "File · Product architecture", lastActivity: "2 hrs ago", status: "Updated", href: "/memory" },
    { id: "continue-4", type: "workspace", title: "Development", context: "Workspace · 4 active agents", lastActivity: "Yesterday", status: "Active", href: "/workspaces/development" },
  ],
  attention: [
    { id: "attention-1", title: "Approve production deployment", detail: "Release 2026.07.20 is waiting for an owner decision", category: "approval", severity: "critical", owner: "Rusty", source: "Sentinel OS", timestamp: "18 min ago", actions: ["approve", "reject", "open"] },
    { id: "attention-2", title: "Typecheck failed in CI", detail: "24 Prisma and authorization errors on the feature build", category: "job", severity: "critical", owner: "Codex", source: "Development", timestamp: "27 min ago", actions: ["open"] },
    { id: "attention-3", title: "Agent requests repository write access", detail: "OpenClaw needs permission to save research artifacts", category: "permission", severity: "high", owner: "Rusty", source: "Research", timestamp: "42 min ago", actions: ["approve", "reject"] },
    { id: "attention-4", title: "Accept interface architecture decision", detail: "Keep Mission Control decision-first and module-neutral", category: "decision", severity: "high", owner: "Hermes Lisa", source: "Sentinel OS", timestamp: "1 hr ago", actions: ["approve", "reject", "open"] },
    { id: "attention-5", title: "Memory candidate ready", detail: "Persist the collapsed rail and separate brand bar preference", category: "memory", severity: "medium", owner: "Knowledge", source: "Organization", timestamp: "2 hrs ago", actions: ["review"] },
    { id: "attention-6", title: "Mission Control tests blocked", detail: "Browser fixture needs an authenticated seed session", category: "task", severity: "medium", owner: "Claude Code", source: "Development", timestamp: "3 hrs ago", actions: ["open"] },
    { id: "attention-7", title: "VPS container restart loop", detail: "sentinel-worker restarted three times in ten minutes", category: "deployment", severity: "low", owner: "Platform", source: "VPS", timestamp: "4 hrs ago", actions: ["open"] },
    { id: "attention-8", title: "Security alert: unusual repository token use", detail: "A token was used from a new network location", category: "security", severity: "high", owner: "Blue Defender", source: "Cybersecurity", timestamp: "5 hrs ago", actions: ["open"] },
  ],
  agents: [
    { id: "hermes-lisa", name: "Hermes Lisa", role: "Lead analyst", status: "online", model: "Claude Sonnet", currentTask: "Synthesizing the morning mission brief", context: "Sentinel OS · Organization", progress: 72, voiceState: "listening", health: { cpu: 18, memory: "1.2 GB", runtime: "6h 42m" }, costToday: 4.82, href: "/agents/hermes-lisa" },
    { id: "claude-code", name: "Claude Code", role: "Software engineer", status: "busy", model: "Claude Sonnet", currentTask: "Refactoring the authentication flow", context: "Sentinel OS · Development", progress: 55, voiceState: "speaking", health: { cpu: 34, memory: "1.8 GB", runtime: "3h 18m" }, costToday: 3.64, href: "/agents/claude-code" },
    { id: "codex", name: "Codex", role: "Code specialist", status: "error", model: "GPT-5", currentTask: "Build failed: type mismatch in utility tests", context: "Sentinel OS · Development", progress: 0, voiceState: "silent", health: { cpu: null, memory: "—", runtime: "Stopped" }, costToday: 2.18, href: "/agents/codex" },
    { id: "openclaw", name: "OpenClaw", role: "Research analyst", status: "offline", model: "Claude Opus", currentTask: "Waiting for repository permission", context: "Research · Security Ops", progress: null, voiceState: "unavailable", health: { cpu: null, memory: "—", runtime: "Offline" }, costToday: 0.94, href: "/agents/openclaw" },
  ],
  feed: [
    { id: "feed-1", scope: "projects", event: "PR #42 merged into feature/final-mission-control", actor: "Claude Code", source: "Sentinel OS", timestamp: "2 min ago", tone: "positive", href: "/projects" },
    { id: "feed-2", scope: "agents", event: "Task completed: Mission Control service architecture", actor: "Hermes Lisa", source: "Sentinel OS", timestamp: "5 min ago", tone: "positive", href: "/agents" },
    { id: "feed-3", scope: "system", event: "Memory created: collapsed rail shell preference", actor: "Knowledge system", source: "Organization", timestamp: "8 min ago", tone: "accent", href: "/memory" },
    { id: "feed-4", scope: "projects", event: "Decision proposed: typed adapters for partial live data", actor: "Codex", source: "Development", timestamp: "12 min ago", tone: "accent", href: "/projects" },
    { id: "feed-5", scope: "agents", event: "Agent error: Codex typecheck stopped", actor: "Codex", source: "Development", timestamp: "18 min ago", tone: "critical", href: "/agents/codex" },
    { id: "feed-6", scope: "system", event: "Deployment completed: sentinel-web", actor: "System", source: "VPS", timestamp: "22 min ago", tone: "positive", href: "/workflows" },
    { id: "feed-7", scope: "organization", event: "Organization invite accepted by Alex Morgan", actor: "Sentinel Admin", source: "Organization", timestamp: "25 min ago", tone: "positive", href: "/orgchart" },
    { id: "feed-8", scope: "workspaces", event: "Campaign outcome created: 17 qualified leads", actor: "Hermes Lisa", source: "Marketing", timestamp: "31 min ago", tone: "neutral", href: "/workspaces/marketing" },
    { id: "feed-9", scope: "system", event: "Security scan finished: no critical findings", actor: "Blue Defender", source: "Cybersecurity", timestamp: "38 min ago", tone: "positive", href: "/workspaces/cybersecurity" },
  ],
  health: [
    { id: "cpu", label: "VPS CPU", status: "healthy", value: "32%", detail: "5.1 / 16 vCPU", utilization: 32 },
    { id: "memory", label: "Memory", status: "healthy", value: "58%", detail: "18.6 / 32 GB", utilization: 58 },
    { id: "disk", label: "Disk", status: "healthy", value: "41%", detail: "410 / 1,000 GB", utilization: 41 },
    { id: "containers", label: "Containers", status: "degraded", value: "12 / 13", detail: "1 restarting" },
    { id: "postgres", label: "PostgreSQL", status: "healthy", value: "24 connections", detail: "v16" },
    { id: "redis", label: "Redis", status: "healthy", value: "128 MB", detail: "v7.2" },
    { id: "network", label: "Network", status: "healthy", value: "78 ↓ / 24 ↑ Mbps", detail: "1.2 Gbps" },
    { id: "active-agents", label: "Active agents", status: "active", value: "3 online", detail: "1 offline" },
    { id: "usage", label: "Token / API usage", status: "healthy", value: "2.4M / 10M", detail: "24%", utilization: 24 },
  ],
  neural: {
    workspace: "Development",
    project: "Sentinel OS",
    repository: "Rustyadj/Sentinel",
    branch: "feature/final-mission-control",
    activeAgentIds: ["hermes-lisa", "claude-code", "codex"],
    nodes: [
      { id: "focus", label: "Sentinel OS", kind: "focus" },
      { id: "hermes", label: "Hermes", kind: "agent" },
      { id: "claude", label: "Claude", kind: "agent" },
      { id: "codex", label: "Codex", kind: "agent" },
      { id: "decision", label: "Decision", kind: "decision" },
      { id: "memory", label: "Memory", kind: "memory" },
      { id: "task", label: "Task", kind: "task" },
    ],
    edges: [
      { from: "focus", to: "hermes" }, { from: "focus", to: "claude" }, { from: "focus", to: "codex" },
      { from: "hermes", to: "decision" }, { from: "claude", to: "task" }, { from: "codex", to: "memory" },
    ],
    counts: { decisions: 3, memories: 28, tasks: 5, blocked: 1 },
  },
  quickActions: [
    { id: "new-project", label: "New Project", href: "/projects", icon: "project" },
    { id: "new-chat", label: "New Chat", href: "/chat", icon: "chat" },
    { id: "voice", label: "Start Voice", href: "/chat?voice=1", icon: "voice" },
    { id: "task", label: "Create Task", href: "/workflows", icon: "task" },
    { id: "invite", label: "Invite Member", href: "/orgchart", icon: "invite" },
    { id: "studio", label: "Open AI Studio", href: "/workspaces/studio", icon: "studio" },
    { id: "module", label: "Install Module", href: "/marketplace", icon: "module" },
    { id: "approval", label: "View Approvals", href: "/workflows", icon: "approval" },
  ],
  liveSources: [],
  mockedSources: ["attention and approvals", "deployment telemetry", "VPS metrics", "agent runtime and cost", "operational activity"],
};
