// Neural Lens — relationship-type display.
//
// Edge types come from two real vocabularies already in use elsewhere in
// Sentinel: KnowledgeEdgeType (lib/knowledge/types.ts) for SCOPED/live data,
// and a small set of structural relationships (part_of, delegates_to,
// references, related_to) this module assigns to the DEMO graph's synthetic
// edges — see demoGraph.ts. This file doesn't invent a third vocabulary; it
// just formats whichever raw type string a LensLink carries into something
// readable, and gives it a display color grouped by rough relationship kind.

const DISPLAY_OVERRIDES: Record<string, string> = {
  part_of: "Part Of",
  depends_on: "Depends On",
  delegates_to: "Delegates To",
  belongs_to: "Belongs To",
  created_by: "Created By",
  assigned_to: "Assigned To",
  generated_by: "Generated By",
  related_to: "Related To",
  triggered_by: "Triggered By",
  learned_from: "Learned From",
  affects_agent: "Affects Agent",
  affects_workspace: "Affects Workspace",
  created_skill: "Created Skill",
  resolved_gap: "Resolved Gap",
  derived_from_trace: "Derived From Trace",
  rolled_back_to: "Rolled Back To",
  approved_by: "Approved By",
  descended_from: "Descended From",
  competes_with: "Competes With",
  evaluated_by: "Evaluated By",
  failed_on: "Failed On",
  promoted_to: "Promoted To",
  distilled_from: "Distilled From",
  protected_by: "Protected By",
  attacked_by: "Attacked By",
};

/** Snake/camel raw edge type → title case for display (e.g. "created_by" →
 * "Created By"). Falls back to a generic label when a link has no type. */
export function formatRelationshipType(type: string | undefined): string {
  if (!type) return "Related To";
  if (DISPLAY_OVERRIDES[type]) return DISPLAY_OVERRIDES[type];
  return type
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[_\s]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
